kind: pipeline
type: kubernetes
name: build

steps:
- name: sync
  image: minio/mc
  environment:
    S3_ACCESS_KEY:
      from_secret: HC_S3_PUBLIC_STATIC_ACCESS_KEY 
    S3_SECRET_KEY:
      from_secret: HC_S3_PUBLIC_STATIC_SECRET_KEY 
    S3_BUCKET:
      from_secret: HC_S3_PUBLIC_STATIC_BUCKET    
    S3_ENDPOINT:
      from_secret: HC_S3_PUBLIC_STATIC_ENDPOINT       
  commands:
  - pip3 install --user -r requirements.txt
  - mkdocs build
  - mc alias set s3 $S3_ENDPOINT $S3_ACCESS_KEY $S3_SECRET_KEY
  - mc mirror --overwrite --remove site/ s3/public-static/$DRONE_REPO_NAME

- name: Lint docs
  image: jdkato/vale
  failure: ignore
  commands:
    - wget https://github.com/errata-ai/Google/releases/download/v0.3.1/Google.zip
    - mkdir .vale
    - unzip Google.zip -d .vale -q
    - vale --glob='!_*' docs

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel:
      from_secret: SLACK_CHANNEL
    template: >
      {{#success build.status}}
        Build <{{build.link}}|{{repo.name}}/{{build.branch}}/#{{build.number}}> *succeeded* in {{since build.started}}
        You can access documentation at:
        <http://cheatsheet.getais.cloud/>
      {{else}}
        Build *failed* <{{build.link}}|{{repo.name}}/{{build.branch}}/#{{build.number}}> Elapsed: {{since build.started}}
      {{/success}}
  when:
    status: [ success, failure ]    
